name: pluto_grid
description: PlutoGrid is a dataGrid that can be controlled by the keyboard on desktop and web. Of course, it works well on Android and IOS. (DataGrid, DataTable, Data Grid, Data Table, Sticky)
version: 1.2.0
homepage: https://bosskmk.github.io
repository: https://github.com/soheilqk/pluto_grid
publish_to: 'none'

environment:
  sdk: ">=2.11.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  rxdart: ^0.26.0
  linked_scroll_controller: ^0.1.2
  pluto_filtered_list: ^0.2.0
  pluto_inside:
    git:
      url: git://github.com/soheilqk/pluto_inside.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

flutter:
  assets:
    - packages/pluto_inside/checkBoxEmpty.png
